type Step {
  stepNum: Int
  description: String
}

type Measurement {
  amount: Int
  unit: String
}

type Ingredient {
  measurement: Measurement
  name: String
  notes: String
}

type Image {
  src: String
  caption: String
}

type Author {
  name: String
  avatar: String
}

type Recipe {
  _id: ID!
  title: String!
  featuredImg: Image!
  quickSummary: String
  author: Author!
  images: [Image!]
  ingredients: [Ingredient!]
  steps: [Step!]
  notes: String
}

input CreateRecipeInput {
  title: String
  quickSummary: String
  notes: String
}

input UpdateRecipeInput {
  title: String
  quickSummary: String
  notes: String
}

type Query {
  recipes: [Recipe!]
  recipe(id: ID!): Recipe
}

type Mutation {
  createRecipe(input: CreateRecipeInput!): Recipe
  updateRecipe(id: ID!, input: UpdateRecipeInput!): Recipe
  deleteRecipe(id: ID!): Int
}
